---
title: "Read All Plays"
output: html_notebook
author: baj
---

Vi kigger på at indlæse alle stykkerne i en samlet dataframe med titler og årstal.

# Read all plays into R

Load the JSONL data format, add title and year, and bind rows

```{r}
library(xml2)
library(tidyverse)
library(ndjson)
library(here)

read_play <- function(page_file, jsonl_file) {
  # read the TEI file to find title and year
  xml_doc <- read_xml(here(page_file))
  
  # <titlePart type="main">
  title <- xml_find_all(
  xml_doc, xpath = "//tei:titlePart[@type='main']",
  ns = c(tei = "http://www.tei-c.org/ns/1.0")
  )
  
  # <titlePart type="sub"> Skal den med?
  
  # <byline rend="center">
  year <- xml_find_all(
  xml_doc, xpath = "//tei:byline[@rend='center']",
  ns = c(tei = "http://www.tei-c.org/ns/1.0")
  )
  
  # read the JSONL file and add title and year as columns
  play <- ndjson::stream_in(here(jsonl_file)) %>% tibble() %>%
      add_column(title = str_squish(xml_text(title)), year = str_squish(xml_text(year)), .before = 0)
  return(play)
}

all_plays <- read_play("data/holberg-komedier-nc/Abracadabra_mod_nc.page", "data/holberg-komedier-nc/json/Abracadabra_mod_nc.jsonl")

all_plays

all_plays <- bind_rows(all_plays,
                       read_play("/test-data/Barselstuen_mod.page", "/test-data/barselstuen_mod.jsonl"))
all_plays

```
We have the read_play function and the bind_rows function. How do we apply this to all the files using list.files rather than doing it by hand?


```{r}

tei_file_list <- list.files(here("/data/holberg-komedier-nc/"), pattern = "*.page")
length(tei_file_list)

json_file_list <- list.files(here("/data/holberg-komedier-nc/json/"))
length(json_file_list)

all_plays <- read_play(str_c("/data/holberg-komedier-nc/",tei_file_list[1]), 
                       str_c("/data/holberg-komedier-nc/json/",json_file_list[1]))

for(i in 2:length(tei_file_list)) {
  tmp <- read_play(str_c("/data/holberg-komedier-nc/",tei_file_list[i]),
                   str_c("/data/holberg-komedier-nc/json/",json_file_list[i]))
  all_plays <- bind_rows(all_plays, tmp)
}

all_plays

write.csv(all_plays, file = here("data/output/all_plays.csv"))

```

